### ISSUE TITLE
Levels higher than 4

### ISSUE THREAD

**Issue by txsutton** [aws-ia/terraform-aws-ipam#54]
We are building an IPAM structure which has more levels than 4
e.g.
- Business Location
- Pool Type (AWS, On-Premise, Azure, etc.)
- AWS Environment
- Business Environment
- Business Unit
- Sub-Business Unit
- etc.

We're currently using your module to create the first 4 levels and then creating terraform resources outside to add the additional layers which issues depends_on issues and adds complexity if we try and update a module and a "manual resource" at the same time.  Is there a better approach? Is there a reason why we are limited to only 4 layers rather than the full 10 that is supported by default? Am I missing something obvious?

**Comment by drewmullen** [comment]
Howdy. Glad to hear this use case! I chose to implement 4 levels for a few reasons:

1. At the time, most customers were only foreseeing 3 levels of depth
2. Terraform doesnt really provide a nice construct for generating nested resources. Essentially we have to parse every pool combination at each level and their relationship to eachother. This yields some really [complicated HCL  ](https://github.com/aws-ia/terraform-aws-ipam/blob/main/main.tf#L11-L12)
3. At some point the usefulness of defining pools in a deeply nested singular map has diminishing returns due to reduced readability.

There are a few options for you that I can think of:

1. consider combining some of your pool levels into a prefix name methodology. aka instead of env -> business env -> bu -> sub-bu you could have `env/business-env` -> `bu/sub-bu`, etc
2. roll your own looping mechanism, using our submodule instead: https://github.com/aws-ia/terraform-aws-ipam/tree/main/modules/sub_pool . This module is basically 2 components, 1st is the looping logic that digests the nested map supplied by callers, 2nd is the submodule which contains all the resources and this is where all the meat is. We have other customers that just call the submodule because we dont fully satisfy their use case.
3. open a feature request for us to start a module invocation at a referenced pre-existing pool. Atm have a notion of invoking the module twice for different `scopes` within the same ipam and setting `create_ipam` to `false`. its possible we could consider a feature where we accept a specific pool id and then you can invoke the module for another 3 pools. To be honest, with this idea, not sure we'd have cycles to focus on that for a while though

**Comment by txsutton** [comment]
Thanks Drew :) - I have implemented Option 2 and it is working well. I do like the idea of option 3 but with the power of option 2 people should be able to workaround it.
